// auth
export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT = "LOGOUT";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

export const SIGNUP = "SIGNUP";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

// plan
export const LOAD_PLAN = "LOAD_PLAN";
export const LOAD_PLAN_SUCCESS = "LOAD_PLAN_SUCCESS";
export const LOAD_PLAN_FAILURE = "LOAD_PLAN_FAILURE";

export const ADD_PLAN = "ADD_PLAN";
export const ADD_PLAN_FAILURE = "ADD_PLAN_FAILURE";
export const ADD_PLAN_SUCCESS = "ADD_PLAN_SUCCESS";

export const DONE_PLAN = "DONE_PLAN";
export const DONE_PLAN_SUCCESS = "DONE_PLAN_SUCCESS";
export const DONE_PLAN_FAILURE = "DONE_PLAN_FAILURE";

export const UPDATE_PLAN = "UPDATE_PLAN";
export const UPDATE_PLAN_SUCCESS = "UPDATE_PLAN_SUCCESS";
export const UPDATE_PLAN_FAIILURE = "UPDATE_PLAN_FAIILURE";

export const DELETE_PLAN = "DELETE_PLAN";
export const DELETE_PLAN_SUCCESS = "DELETE_PLAN_SUCCESS";
export const DELETE_PLAN_FAILURE = "DELETE_PLAN_FAILURE";

// post

export const LOAD_BOARD = "LOAD_BOARD";
export const LOAD_BOARD_SUCCESS = "LOAD_BOARD_SUCCESS";
export const LOAD_BOARD_FAILURE = "LOAD_BOARD_FAILURE";

export const ADD_BOARD = "ADD_BOARD";
export const ADD_BOARD_SUCCESS = "ADD_BOARD_SUCCESS";
export const ADD_BOARD_FAILURE = "ADD_BOARD_FAILURE";

export const DELETE_BOARD = "DELETE_POST";
export const DELETE_BOARD_SUCCESS = "DELETE_BOARD_SUCCESS";
export const DELETE_BOARD_FAILURE = "DELETE_BOARD_FAILURE";

export const UPDATE_BOARD = "UPDATE_BOARD";
export const UPDATE_BOARD_SUCCESS = "UPDATE_BOARD_SUCCESS";
export const UPDATE_BOARD_FAILURE = "UPDATE_BOARD_FAILURE";

export const UPLOAD_IMAGE = "UPLOAD_IMAGE";
export const UPLOAD_IMAGE_SUCCESS = "UPLOAD_IMAGE_SUCCESS";
export const UPLOAD_IMAGE_FAILURE = "UPLOAD_IMAGE_FAILURE";
